import Header from '@/components/layout/Header';
import './globals.css';
import Footer from '@/components/layout/Footer';
import ScrollToTop from '@/components/layout/ScrollToTop';
import Main from '@/components/layout/Main';
import Head from './head';
//font 추가
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <Head />
      <body>
        <ScrollToTop />
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
